templates/hello/simple-snippet.html
@Osmose added an additional event listener per Alex's comment in IRC.
=> [fix bug 1115229] Hide menu on window resize (ref bug 1091785)

video-snippets/simple-over-search-bar.html
https://bugzilla.mozilla.org/show_bug.cgi?id=1140456
Inspired from
https://github.com/mozilla/snippets/blob/master/templates/10th-anniversary-video/10th-anniversary-video-no-share.html
=> [fix bug 1140456] Create simple video snippet

templates/logo-replacement-with-share.html
https://bugzilla.mozilla.org/show_bug.cgi?id=1164669
=> [fix bug 1164669] Share snippet with optional logo replacement

video-snippets/share-over-search-bar.html
https://bugzilla.mozilla.org/show_bug.cgi?id=1144943
https://snippets.allizom.org/show/87/
=> [fix bug 1144943] Create Video snippet with FB and TW sharing

templates/logo-replacement-with-share.html
* Sorry for the 3 PR's, did this one quickly through the GH UI.
=> Modify metrics to match naming convention

android/android-email-sms.html
https://bugzilla.mozilla.org/show_bug.cgi?id=1137290
https://snippets.allizom.org/show/90/
=> [bug 1137290] Android SMS and Email snippet

android/android-email-sms-configure.html
This is a clone of #44 with the exception of allowing the admin to configure the SMS and Email ID's.
Sample is https://snippets.allizom.org/show/91/
Bug is https://bugzilla.mozilla.org/show_bug.cgi?id=1177829
=> [fix bug 1177829] Android SMS/Email with configurable IDs

templates/pocket/simple.html
https://bugzilla.mozilla.org/show_bug.cgi?id=1163690
https://snippets.allizom.org/show/86/
=> [fix bug 1163690] Pocket simple snippet

generic-templates/simple-snippet.html
Changes in simple snippet and logo swap snippet with close button, to make the button appear over the text as designed here https://bugzilla.mozilla.org/show_bug.cgi?id=1172579#c15
Fixes https://bugzilla.mozilla.org/show_bug.cgi?id=1172579#c31 point 1
@schalkneethling r?
=> Update simple snippet

campaigns/private-browsing/simple.html
This is snippet 1 of 3 for Private Browsing. See [bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1206861) for full specs.
This is dependent on https://github.com/mozilla/snippets-service/pull/122 being pushed to production.
Stage: https://snippets.allizom.org/admin/base/snippet/95/
=> [bug 1206861] PB Simple Snippet (1of2)

campaigns/private-browsing/logo-swap.html
This is snippet 2 of 3 for Private Browsing. See bug for full specs.
Stage: https://snippets.allizom.org/admin/base/snippet/96/
=> [bug 1206861] PB Logo Swap (2of2)

campaigns/mofo-eoy-2016/snippet.html
Fixing https://github.com/MozillaFoundation/Advocacy/issues/643 for the upcoming Italian translation (and potentially other languages)
=> Horizontal padding for longer translations

generic-templates/newsletter-signup-snippet/snippet.html
@glogiotatidis ping
Been working on this from time to time when I had free moments.
Ticket for context: https://github.com/MozillaFoundation/Advocacy/issues/588
Apology for the large ticket :(
Thoughts? Review?
🚀 🚀
=> Adding updated Basket sigup snippet.

campaigns/mofo-eoy-2016/snippet.html
=> Fix C-click and option to skip auto-blocking

generic-templates/simple-snippet.html
Move button and icon to the left and right accordingly if rtl is checked.
=> Extend support for RTL languages

generic-templates/simple-snippet.html
@glogiotatidis Here are a few changes that we talked about. Still waiting on a response from Jean.
1. Some updated alignment.
2. New overlay.
3. Overlay and opt out transitions.
I sent Jean an email, and a short video of the snippet in action so she can get an idea, and pinged shorlander to make sure it's still what he wanted/didn't want to make any updates.
shorlander was fine with it. Still waiting on Jean (I just sent the email, I don't expect a response back tonight)
Once I hear back from Jean I'll update this ticket and ping you.
Let me know if you have any questions! Here is the original demo for reference: https://people-mozilla.org/%7Eshorlander/about-home-snippet-opt-out/about-home-test-01.html
=> Generic snippet overlay and opt out button design changes.

campaigns/mobile/mobile-snippet-widget.html
@glogiotatidis hey, pretty simple patch here. I hope I got everything.
A few things to mention.
1. I believe Wes Winton was going to ping you with context for this. I don't have much.
2. I'm just adding some background optional prop to the mobile-snippet-widget
3. I wasn't sure what mobile-snippet-widget-200 was, so I just left it as is.
4. Finally, there wasn't much in terms of documentation in this snippet, so I didn't add to it.
Thoughts?
=> Background option for mobile snippet widget.

campaigns/thank-you/snippet.html
@glogiotatidis Not an official pull request yet, just a work in progress.
The reason I'm sending this to you now is I was experimenting with a height transition during the snippet load process and wanted to get your thoughts.
It only works in this snippet, so if we wanted it in another snippet we would need to build it into that snippet, which isn't great, but works as a test or experiment at the least.
The yml I used for this is as follows:
~~~
header_image: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAjAAAABoCAYAAADvs8rcAAAgAElEQVR4nO2d51uTydfHf/8JuhYC2/uza9nmutWtbu+uYl3bqqtrlxJAWui9J3RIQGk2REQEUbqgNOkgqPQavs8L4E4mdwLJkAY757rOK6+LM3Nmcp+PM2fO+Z+1JBVMmTJlypQpU6YLSf9n6gEwZcqUKVOmTJnqqgxgmDJlypQpU6YLThnAMGXKlClTpkwXnDKAYcpUg1pFS2EZGs/pS5EJeD8xidONqeex89JVrXTHpVzsvHyN0+2Xr+HPbIV+n56jtzELw …
=> Thank you snippet

activity-stream/simple-snippet.html
These are some changes I worked on with Aaron.  Depends on https://github.com/mozmeao/snippets-service/pull/293. Here are some screenshots:
=> Update simple snippet (activity stream) with new styles

activity-stream/newsletter-subscribe.html, activity-stream/send-to-device.html
@glogiotatidis - Along with general review, there's a question for you (commented in code) regarding the availability/use of `{{ snippet_id }}`.
=> [fix bug 1404542] Adds a send to device snippet for AS.

activity-stream/send-to-device.html
Fixes mozmeao/snippets-service#358.
=> [fix #358] Send lang w/email request on send to device AS snippet.

activity-stream/fxa.html, activity-stream/newsletter-subscribe.html, activity-stream/send-to-device.html, activity-stream/simple-video-snippet.html
Follow up to https://github.com/mozmeao/snippets-service/pull/610 not sure if these are still in use but just to be sure.
=> Use inset-* alongside offset-* properties to support both nightly and release channels

activity-stream/fxa.html, activity-stream/mofo-eoy-2017.html, activity-stream/newsletter-subscribe.html, activity-stream/send-to-device.html, activity-stream/simple-snippet.html, activity-stream/simple-video-snippet.html
Fix https://github.com/mozmeao/snippets-service/issues/636
=> All AS templates must be blockable.

activity-stream/send-to-device-card.html
- Fix Play Store link color
- Small default string changes for error message and privacy link
- Remove 'sending' button state
- Re-work 'sent' button state
=> [fix #661] Update send to device card template (part 2):

activity-stream/mofo-eoy-2017.html
Issue https://github.com/mozmeao/snippets-service/issues/755
=> Automatically block snippet after donate button gets clicked.
